name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.16"

      - name: Run Go fmt
        run: go fmt ./...

      - name: Run Go vet
        run: go vet ./...

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: go build -v

      - name: Test
        run: go test -v ./...
